---
title: "Clustering jerarquico"
output: html_notebook
---
Primero pongo un ejemplo de dendrograma y una clasificaci칩n jer치rquica. Busque unos datos peque침os para que se vea algo en el dendrograma
```{r}
  source("01_setup.R")
  dataset<-'data/artificial/aggregation.arff'
  X<-read.arff(dataset)
  k<-nlevels(X$class)
  k
  method <- 'complete'
  C_h <- X %>% select(c(1:2)) %>% dist() %>% hclust(method)
  #dendrograma
  dend <- fviz_dend(x = C_h,k = k, labels_track_height = 0, rect = TRUE)

  partition_h<-cutree(C_h,k)
  X <- mutate(X, hc = factor(partition_h))
  plot_h <- ggplot(data = X)+geom_point(mapping = aes(x = X[,1], y = X[,2], color = hc)) +
    labs(title = "Partici칩n para k = 7", colour = "Clusters") + theme(axis.title = element_blank())
  plot_real <- ggplot(data = X)+geom_point(mapping = aes(x = X[,1], y = X[,2], color = class)) + labs(title = "Real Data Distribution", colour = "Clusters") + theme(axis.title.x = element_blank(), axis.title.y = element_blank())
  grid.arrange(plot_h,dend,ncol = 2)
 
```
Quiero ver el chain effect del single link y como el complete link lo hace mejor en esos casos

```{r}

#Quiero leer el archivo de datos primero
dataset<-'data/artificial/diamond9.arff'
X<-read.arff(dataset)
source("10_hclust.R")

method<-'single' #metodos: complete, single, average, centroids
X <- h_clustering(X,method,9)
#solucion del jerarquico
plot_h_s <- ggplot(data = X)+geom_point(mapping = aes(x = X[,1], y = X[,2], color = hc)) + labs(colour = "Clusters", title = "Single Link") + theme(axis.title = element_blank())
method<-'complete' #metodos: complete, single, average, centroids
X <- h_clustering(X,method,9)
#solucion del jerarquico
plot_h_c <- ggplot(data = X)+geom_point(mapping = aes(x = X[,1], y = X[,2], color = hc)) + labs(colour = "Clusters", title = "Complete Link") + theme(axis.title = element_blank())
grid.arrange(plot_h_c,plot_h_s,
             ggplot(data = X) + geom_point(mapping = aes(x = X[,1], y = X[,2], color = class)) + labs(colour = "Clusters", title = "Real Data Distribution") + theme(axis.title = element_blank()),
             ncol = 3)
```